// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zdb_coreFFI)
import zdb_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zdb_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zdb_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureZdbCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * High-level facade composing GitRepo + Index for mobile/desktop FFI consumers.
 */
public protocol ZettelDriverProtocol: AnyObject, Sendable {
    
    func attachFile(zettelId: String, filePath: String) throws  -> AttachmentInfo
    
    func compact() throws 
    
    func createZettel(content: String, message: String) throws  -> String
    
    func deleteZettel(id: String, message: String) throws 
    
    func detachFile(zettelId: String, filename: String) throws 
    
    func executeSql(sql: String) throws  -> String
    
    func exportFullBundle(outputPath: String) throws  -> String
    
    func importBundle(bundlePath: String) throws 
    
    func listAttachments(zettelId: String) throws  -> [AttachmentInfo]
    
    func listZettels() throws  -> [String]
    
    func readZettel(id: String) throws  -> String
    
    func reindex() throws  -> RebuildReport
    
    func search(query: String) throws  -> [SearchResult]
    
    func searchPaginated(query: String, limit: UInt32, offset: UInt32) throws  -> PaginatedSearchResult
    
    func updateZettel(id: String, content: String, message: String) throws 
    
}
/**
 * High-level facade composing GitRepo + Index for mobile/desktop FFI consumers.
 */
open class ZettelDriver: ZettelDriverProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zdb_core_fn_clone_zetteldriver(self.pointer, $0) }
    }
public convenience init(repoPath: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_constructor_zetteldriver_new(
        FfiConverterString.lower(repoPath),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zdb_core_fn_free_zetteldriver(pointer, $0) }
    }

    

    
open func attachFile(zettelId: String, filePath: String)throws  -> AttachmentInfo  {
    return try  FfiConverterTypeAttachmentInfo_lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_attach_file(self.uniffiClonePointer(),
        FfiConverterString.lower(zettelId),
        FfiConverterString.lower(filePath),$0
    )
})
}
    
open func compact()throws   {try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_compact(self.uniffiClonePointer(),$0
    )
}
}
    
open func createZettel(content: String, message: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_create_zettel(self.uniffiClonePointer(),
        FfiConverterString.lower(content),
        FfiConverterString.lower(message),$0
    )
})
}
    
open func deleteZettel(id: String, message: String)throws   {try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_delete_zettel(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(message),$0
    )
}
}
    
open func detachFile(zettelId: String, filename: String)throws   {try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_detach_file(self.uniffiClonePointer(),
        FfiConverterString.lower(zettelId),
        FfiConverterString.lower(filename),$0
    )
}
}
    
open func executeSql(sql: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_execute_sql(self.uniffiClonePointer(),
        FfiConverterString.lower(sql),$0
    )
})
}
    
open func exportFullBundle(outputPath: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_export_full_bundle(self.uniffiClonePointer(),
        FfiConverterString.lower(outputPath),$0
    )
})
}
    
open func importBundle(bundlePath: String)throws   {try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_import_bundle(self.uniffiClonePointer(),
        FfiConverterString.lower(bundlePath),$0
    )
}
}
    
open func listAttachments(zettelId: String)throws  -> [AttachmentInfo]  {
    return try  FfiConverterSequenceTypeAttachmentInfo.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_list_attachments(self.uniffiClonePointer(),
        FfiConverterString.lower(zettelId),$0
    )
})
}
    
open func listZettels()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_list_zettels(self.uniffiClonePointer(),$0
    )
})
}
    
open func readZettel(id: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_read_zettel(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func reindex()throws  -> RebuildReport  {
    return try  FfiConverterTypeRebuildReport_lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_reindex(self.uniffiClonePointer(),$0
    )
})
}
    
open func search(query: String)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func searchPaginated(query: String, limit: UInt32, offset: UInt32)throws  -> PaginatedSearchResult  {
    return try  FfiConverterTypePaginatedSearchResult_lift(try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_search_paginated(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
open func updateZettel(id: String, content: String, message: String)throws   {try rustCallWithError(FfiConverterTypeZdbError_lift) {
    uniffi_zdb_core_fn_method_zetteldriver_update_zettel(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(content),
        FfiConverterString.lower(message),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZettelDriver: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ZettelDriver

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ZettelDriver {
        return ZettelDriver(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ZettelDriver) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZettelDriver {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ZettelDriver, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZettelDriver_lift(_ pointer: UnsafeMutableRawPointer) throws -> ZettelDriver {
    return try FfiConverterTypeZettelDriver.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZettelDriver_lower(_ value: ZettelDriver) -> UnsafeMutableRawPointer {
    return FfiConverterTypeZettelDriver.lower(value)
}




/**
 * FFI-safe attachment metadata.
 */
public struct AttachmentInfo {
    public var name: String
    public var mime: String
    public var size: UInt64
    public var path: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, mime: String, size: UInt64, path: String) {
        self.name = name
        self.mime = mime
        self.size = size
        self.path = path
    }
}

#if compiler(>=6)
extension AttachmentInfo: Sendable {}
#endif


extension AttachmentInfo: Equatable, Hashable {
    public static func ==(lhs: AttachmentInfo, rhs: AttachmentInfo) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.mime != rhs.mime {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(mime)
        hasher.combine(size)
        hasher.combine(path)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttachmentInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AttachmentInfo {
        return
            try AttachmentInfo(
                name: FfiConverterString.read(from: &buf), 
                mime: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                path: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AttachmentInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.mime, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttachmentInfo_lift(_ buf: RustBuffer) throws -> AttachmentInfo {
    return try FfiConverterTypeAttachmentInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttachmentInfo_lower(_ value: AttachmentInfo) -> RustBuffer {
    return FfiConverterTypeAttachmentInfo.lower(value)
}


/**
 * FFI-safe paginated search result.
 */
public struct PaginatedSearchResult {
    public var hits: [SearchResult]
    public var totalCount: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hits: [SearchResult], totalCount: UInt64) {
        self.hits = hits
        self.totalCount = totalCount
    }
}

#if compiler(>=6)
extension PaginatedSearchResult: Sendable {}
#endif


extension PaginatedSearchResult: Equatable, Hashable {
    public static func ==(lhs: PaginatedSearchResult, rhs: PaginatedSearchResult) -> Bool {
        if lhs.hits != rhs.hits {
            return false
        }
        if lhs.totalCount != rhs.totalCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hits)
        hasher.combine(totalCount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePaginatedSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PaginatedSearchResult {
        return
            try PaginatedSearchResult(
                hits: FfiConverterSequenceTypeSearchResult.read(from: &buf), 
                totalCount: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PaginatedSearchResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSearchResult.write(value.hits, into: &buf)
        FfiConverterUInt64.write(value.totalCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaginatedSearchResult_lift(_ buf: RustBuffer) throws -> PaginatedSearchResult {
    return try FfiConverterTypePaginatedSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaginatedSearchResult_lower(_ value: PaginatedSearchResult) -> RustBuffer {
    return FfiConverterTypePaginatedSearchResult.lower(value)
}


/**
 * FFI-safe rebuild report.
 */
public struct RebuildReport {
    public var indexed: UInt64
    public var tablesMaterialized: UInt64
    public var typesInferred: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(indexed: UInt64, tablesMaterialized: UInt64, typesInferred: [String]) {
        self.indexed = indexed
        self.tablesMaterialized = tablesMaterialized
        self.typesInferred = typesInferred
    }
}

#if compiler(>=6)
extension RebuildReport: Sendable {}
#endif


extension RebuildReport: Equatable, Hashable {
    public static func ==(lhs: RebuildReport, rhs: RebuildReport) -> Bool {
        if lhs.indexed != rhs.indexed {
            return false
        }
        if lhs.tablesMaterialized != rhs.tablesMaterialized {
            return false
        }
        if lhs.typesInferred != rhs.typesInferred {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(indexed)
        hasher.combine(tablesMaterialized)
        hasher.combine(typesInferred)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRebuildReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RebuildReport {
        return
            try RebuildReport(
                indexed: FfiConverterUInt64.read(from: &buf), 
                tablesMaterialized: FfiConverterUInt64.read(from: &buf), 
                typesInferred: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: RebuildReport, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.indexed, into: &buf)
        FfiConverterUInt64.write(value.tablesMaterialized, into: &buf)
        FfiConverterSequenceString.write(value.typesInferred, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRebuildReport_lift(_ buf: RustBuffer) throws -> RebuildReport {
    return try FfiConverterTypeRebuildReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRebuildReport_lower(_ value: RebuildReport) -> RustBuffer {
    return FfiConverterTypeRebuildReport.lower(value)
}


/**
 * FFI-safe search result.
 */
public struct SearchResult {
    public var id: String
    public var title: String
    public var path: String
    public var snippet: String
    public var rank: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, path: String, snippet: String, rank: Double) {
        self.id = id
        self.title = title
        self.path = path
        self.snippet = snippet
        self.rank = rank
    }
}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif


extension SearchResult: Equatable, Hashable {
    public static func ==(lhs: SearchResult, rhs: SearchResult) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.snippet != rhs.snippet {
            return false
        }
        if lhs.rank != rhs.rank {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(path)
        hasher.combine(snippet)
        hasher.combine(rank)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                snippet: FfiConverterString.read(from: &buf), 
                rank: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.snippet, into: &buf)
        FfiConverterDouble.write(value.rank, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


/**
 * FFI error enum exposed to Swift/Kotlin via UniFFI.
 */
public enum ZdbError: Swift.Error {

    
    
    case Git(msg: String
    )
    case Yaml(msg: String
    )
    case Sql(msg: String
    )
    case Automerge(msg: String
    )
    case Io(msg: String
    )
    case Parse(msg: String
    )
    case NotFound(msg: String
    )
    case Config(msg: String
    )
    case Validation(msg: String
    )
    case SqlEngine(msg: String
    )
    case VersionMismatch(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZdbError: FfiConverterRustBuffer {
    typealias SwiftType = ZdbError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZdbError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Git(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Yaml(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Sql(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Automerge(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Parse(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 7: return .NotFound(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 8: return .Config(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 9: return .Validation(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 10: return .SqlEngine(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 11: return .VersionMismatch(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ZdbError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Git(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Yaml(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Sql(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Automerge(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Io(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Parse(msg):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NotFound(msg):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Config(msg):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Validation(msg):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .SqlEngine(msg):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .VersionMismatch(msg):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZdbError_lift(_ buf: RustBuffer) throws -> ZdbError {
    return try FfiConverterTypeZdbError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZdbError_lower(_ value: ZdbError) -> RustBuffer {
    return FfiConverterTypeZdbError.lower(value)
}


extension ZdbError: Equatable, Hashable {}




extension ZdbError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAttachmentInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AttachmentInfo]

    public static func write(_ value: [AttachmentInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAttachmentInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AttachmentInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [AttachmentInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAttachmentInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zdb_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_attach_file() != 1297) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_compact() != 17122) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_create_zettel() != 29578) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_delete_zettel() != 11467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_detach_file() != 55487) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_execute_sql() != 61268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_export_full_bundle() != 37132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_import_bundle() != 52952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_list_attachments() != 50289) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_list_zettels() != 8000) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_read_zettel() != 64177) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_reindex() != 9955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_search() != 27489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_search_paginated() != 30262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_method_zetteldriver_update_zettel() != 62395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zdb_core_checksum_constructor_zetteldriver_new() != 14310) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureZdbCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all