[book]
authors = ["Tomáš Bouška"]
language = "en"
src = "src"
title = "Doogat ZettelDB Documentation"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/doogat/zetteldb"
